- name: Condition demo
  hosts: localhost
  connection: local
  tasks:
    - name: x is greater then 10
      ansible.builtin.debug:
        msg: "x is greater than 10"
      when: x| int >10
    
    - name: x is less then 10
      ansible.builtin.debug:
        msg: "x is less than 10"
      when: x|int < 10

#when does not need {{}}