- name: get secrets
  hosts: localhost
  connection: local
  tasks:
    - name: print
      ansible.builtin.debug:
         msg: "{{ lookup('community.hashi_vault.hashi_vault', secret=test/demo:username token={{ vault_token}} url=http://vault-internal.kommanuthala.store:8200') }} "
        # msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=test/demo:username token={{ vault_token }} url=http://vault-internal.kommanuthala.store:8200') }}"